### ISSUE TITLE
How to sort "Date" column in cross table

### ISSUE THREAD

**Issue by BCT-ok** [BCT-ok/BCT-Analytics#6]
I have created an Cross Table from time series data, where date is added as a column. By default the date is ascending in order. I want to set the date in descending order, showing latest date/month/year on top.
Reference: 
![image](https://github.com/BCT-ok/BCT-Analytics/assets/145122192/07a84541-d2aa-439f-824f-5efd25052308)

**Comment by ashishmauryabct** [comment]
You can find the solution at this link,

https://support.tibco.com/s/article/How-to-sort-a-date-column-in-descending-order-in-a-Cross-Table

**Comment by ashishmauryabct** [comment]
#8
